### ISSUE TITLE
log information wrong, or argument parsing error

### ISSUE THREAD

**Issue by TCLamnidis** [stschiff/rarecoal#1] opened 2020-02-18 17:51 UTC
rarecoal produces a log that states the parameters specified for a run. Although the default `minAf` and `maxAf` are 1 and 4 respectively (according to `--help`), the log information seems to always say:
```
MinAf: 1
MaxAf: 10
```

This is either a problem with parsing the CLI arguments or with printing out the correct values for the parsed arguments in the logfile.

Also:
```
  --minAf INT              minimal allele count (default: 1)
  -m,--max_af INT          maximum allele count (default: 4)
```
 The options do not follow the same naming rules. I would suggest changing he option names so they match one another (`--minAf` & `--maxAf` or `--min_af` & `--max_af`)

**Comment by TCLamnidis** [comment] 2020-02-18 17:54
I tried both running rarecoal mcmc without specifying these values, and by specifying `--minAf 2 --max_af 4`. Both runs contained the same info in the logfile.

**Comment by stschiff** [comment] 2020-03-10 16:23
I'm looking into this. It's a bit of a puzzle actually. Thanks for flagging this.

**Comment by stschiff** [comment] 2020-03-10 21:01
I cannot reproduce this. I just installed the latest rarecoal directly from GitHub and ran
```
rarecoal logl -T exampleData/fourPop.template.txt -i exampleData/fourPop.histogram.txt -P exampleData/fourPop.m4.mcmc.paramEstimates.txt
```
from within the rarecoal directory. The output includes
```
MinAf: 1
MaxAf: 4
```
as it should. Are you using an old version or something?

**Comment by stschiff** [comment] 2020-03-17 12:48
Closing for now, as it doesn't seem to be a bug in the most recent version. Feel free to re-open if you have new insights about what version has this bug.

**Closed as completed by stschiff** 2020-03-17 12:48 UTC
Labels: bug
